spring.application.name=costos-reposteria-backend

# Configuración del Puerto (React suele usar el 3000, dejaremos Spring en el 8080)
#server.port=8080

# Conexión a MySQL
#spring.datasource.url=jdbc:mysql://localhost:3306/costos_reposteria?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=sasa

# Configuración de JPA / Hibernate
# Esto permite que Hibernate actualice la tabla si cambias algo en el código Java
#spring.jpa.hibernate.ddl-auto=update
# Esto es para ver las consultas SQL en la consola (útil para aprender/depurar)
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


server.port=8080
# Usamos variables que Render rellenará
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Configuraciones extra para que funcione bien en la nube
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver